name: Publish NuGet Package

on:
  release:
    types: [ "published" ]

env:
  solution_path: './Features.sln'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        dotnet-framework: [ 'net8.0', 'net9.0' ]
    steps:
      - name: Restore dependencies
        run: dotnet restore ${{ env.solution_path }}

      - name: Build
        run: dotnet build ${{ env.solution_path }} --configuration Release --no-restore --framework ${{ matrix.dotnet-framework }}
  pack_and_publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pack
        run: dotnet pack ${{ env.solution_path }} --configuration Release --no-build --output ./nupkgs
      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "nupkgs/*.nupkg" -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
